packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@cloudflare/workers-types': ^4.20250917.0
  '@hattip/core': ^0.0.49
  '@hattip/router': ^0.0.49
  '@swc/core': ^1.13.5
  '@types/express': ^5.0.3
  '@types/node': ^20.19.16
  '@webroute/route': ^0.8.0
  elysia: ^1.4.5
  express: ^5.1.0
  fastify: ^5.6.1
  h3: ^1.15.4
  hono: ^4.9.7
  rimraf: ^6.0.1
  srvx: ^0.8.7
  tsup: ^8.5.0
  tsx: ^4.20.5
  typescript: ^5.9.2
  vite: ^7.1.5
  vitest: ^3.2.4
  wrangler: ^4.37.1
