autoInstallPeers: false
linkWorkspacePackages: deep
packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@cloudflare/workers-types': ^4.20260114.0
  '@hattip/core': ^0.0.49
  '@hattip/router': ^0.0.49
  '@swc/core': ^1.15.8
  '@types/express': ^5.0.6
  '@types/node': ^20.19.29
  '@webroute/route': ^0.8.0
  elysia: ^1.4.22
  express: ^5.2.1
  fastify: ^5.6.2
  h3: ^1.15.4
  hono: ^4.11.4
  rimraf: ^6.1.2
  srvx: ^0.10.0
  tsdown: ^0.20.0-beta.3
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^7.3.1
  vitest: ^4.0.17
  wrangler: ^4.59.1
