packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@cloudflare/workers-types': ^4.20251205.0
  '@hattip/core': ^0.0.49
  '@hattip/router': ^0.0.49
  '@swc/core': ^1.15.3
  '@types/express': ^5.0.6
  '@types/node': ^20.19.21
  '@webroute/route': ^0.8.0
  elysia: ^1.4.18
  express: ^5.2.1
  fastify: ^5.6.2
  h3: ^1.15.4
  hono: ^4.10.7
  rimraf: ^6.1.2
  srvx: ^0.9.7
  tsup: ^8.5.1
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^7.2.7
  vitest: ^4.0.15
  wrangler: ^4.53.0
