packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@cloudflare/workers-types': ^4.20251118.0
  '@hattip/core': ^0.0.49
  '@hattip/router': ^0.0.49
  '@swc/core': ^1.15.2
  '@types/express': ^5.0.5
  '@types/node': ^20.19.21
  '@webroute/route': ^0.8.0
  elysia: ^1.4.16
  express: ^5.1.0
  fastify: ^5.6.2
  h3: ^1.15.4
  hono: ^4.10.6
  rimraf: ^6.1.0
  srvx: ^0.9.6
  tsup: ^8.5.1
  tsx: ^4.20.6
  typescript: ^5.9.3
  vite: ^7.2.2
  vitest: ^4.0.10
  wrangler: ^4.47.0
