autoInstallPeers: false
linkWorkspacePackages: deep
packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@cloudflare/workers-types': ^4.20260214.0
  '@hattip/core': ^0.0.49
  '@hattip/router': ^0.0.49
  '@swc/core': ^1.15.11
  '@types/express': ^5.0.6
  '@types/node': ^20.19.33
  '@webroute/route': ^0.8.0
  elysia: ^1.4.25
  express: ^5.2.1
  fastify: ^5.7.4
  h3: ^1.15.5
  hono: ^4.11.9
  rimraf: ^6.1.3
  srvx: ^0.11.4
  tsup: ^8.5.1
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^7.3.1
  vitest: ^4.0.18
  wrangler: ^4.65.0
