packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@cloudflare/workers-types': ^4.20250428.0
  '@hattip/core': ^0.0.49
  '@hattip/router': ^0.0.49
  '@swc/core': ^1.11.22
  '@types/express': ^5.0.1
  '@types/node': ^20.17.30
  '@webroute/route': ^0.8.0
  elysia: ^1.2.25
  express: ^5.1.0
  fastify: ^5.3.2
  h3: ^1.15.2
  hono: ^4.7.8
  rimraf: ^6.0.1
  tsup: ^8.4.0
  tsx: ^4.19.3
  typescript: ^5.8.3
  vite: ^6.3.3
  vitest: ^3.1.2
  wrangler: ^4.13.2
