packages:
  - packages/*
  - examples/*
  - tests-examples/*
  - docs
catalog:
  '@hattip/router': ^0.0.48
  '@swc/core': ^1.7.39
  '@types/express': ^4.17.21
  '@types/node': ^20.17.0
  elysia: ^1.1.23
  express: ^4.21.1
  fastify: ^5.0.0
  h3: ^1.13.0
  hono: ^4.6.6
  rimraf: ^6.0.1
  tsup: ^8.3.0
  tsx: ^4.19.1
  typescript: ^5.6.3
  vite: ^5.4.10
  vitest: ^2.1.3
  wrangler: ^3.83.0
